# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_price', models.CharField(max_length=200)),
                ('device_memory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('device_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Devices'),
        ),
    ]
