# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedetails',
            old_name='device',
            new_name='devices',
        ),
    ]
